=== Rud5G/namm-json/schema/functional_ack.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "https://standards.namm.org/schema/2020.1/functional_ack.json",
  "type": "object",
  "title": "NAMM Functional Acknowledgement",
  "description": "This is a json-schema version of NAMM Functional Ack XSD",
  "$comment": "Additional properties has been set to true to optionally allow reporting back of additional information such as order number",
  "additionalProperties": true,
  "properties": {
      "Version": {
          "$ref": "https://standards.namm.org/schema/2020.1/common.json#/definitions/Version"
      },
      "Id": {
          "type": "string",
          "description": "Document ID",
          "maxLength": 50
      },
      "Timestamp": {
          "type": "string",
          "description": "Date/time stamp for this document",
          "format": "date-time"
      },
      "Supplier": {
        "$ref": "https://standards.namm.org/schema/2020.1/common.json#/definitions/Party"
      },
      "SoldTo": {
        "$ref": "https://standards.namm.org/schema/2020.1/common.json#/definitions/Party"
      },
      "StatusCode" : {
        "type": "string",
        "enum": [
            "C01",
            "C02"
          ]
      },
      "StatusMessage" : {
        "type" : "string",
        "description": "Additional information about status",
        "maxLength": 255
      }
    
    }
  }

=== Rud5G/namm-json/examples/functional_ack_example.json
{
  "Version": 2020.1,
  "Id": "0417b55c-d510-4a22-aa9b-5cfe9323de94",
  "Timestamp": "2021-07-27T22:53:22.86",
  "SoldTo": {
    "PartyId": "1100001001675",
    "PartyIdType": "GLN",
    "Name": "Joe's Music Store"
  },
  "Supplier": {
    "PartyId": "0670716000009",
    "PartyIdType": "GLN",
    "Name": "Korg USA Inc."
  },
  "StatusCode": "C01",
  "StatusMessage": "Received"
}
