=== Rud5G/namm-json/schema/POStatusRequest-v2015.1.schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "type": "object",
    "title": "NAMM_POStatusRequest",
    "additionalProperties": false,
    "properties": {
        "version": {
            "type": "number",
            "enum": [
                2015.1
            ]
        },
        "Id": {
            "type": "string",
            "description": "Document ID"
        },
        "Timestamp": {
            "type": "string",
            "description": "Document Time stamp",
            "format": "date-time"
        },
        "Supplier": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "PartyId": {
                    "type": "string"
                }
            },
            "required": [
                "PartyId"
            ]
        },
        "SoldTo": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "PartyId": {
                    "type": "string"
                }
            },
            "required": [
                "PartyId"
            ]
        },
        "BuyerOrderIds": {
            "type": "array",
            "items": {
                "type": "string"
            }
        }
    },
    "required": []
}

=== Rud5G/namm-json/examples/PO_StatusRequest.json
{

    "version": 2015.1,
    "Timestamp": "2011-07-19T10:34:02",
    "Id": "S2S3050_PO691630-1",
    "Supplier": {
      "PartyId": "0761294001004"
    },
    "SoldTo": {
      "PartyId": "1100001001675"
    },
    "BuyerOrderIds":  [
        "123456",
        "987654",
        "654321"
      ]
    

}
